Natural language processing of time.  Add --timeframe, dev logging, d…
logdna/logdna-cli pull request #49
Opened 2021-06-01 17:17 UTC by braxtonj

…oc updates

Added natural language processing to search via Chrono library

Extended search to use --timeframe for full range parsing and incorporated nl into --from and --to

Added doc examples explaining use.  Added help to search to include NL explanation.

Added developer logs using best practices (5Ws - who, what, why, where, and when) that sends to console AND LogDNA for troubleshooting.  Simple flag in /lib/config.js to turn developer logging on and off.  LOGDNA_API_KEY environment variable required to use developer logging.

TODO: Dev logs currently only in index.js.  Extend for full coverage

TODO: allow for implied date reference ("7PM" instead of "today at 7PM")

TODO: systematic testing

2021-06-01 17:30 UTC, esatterwhite commented on index.js
> +    devLog.why = 'uncaught exception - '+err.message;
Rather than pre-allocate this, I would just define this in the function when it happens.
you have to re-define all of the properties anyway.

2021-06-01 17:31 UTC, esatterwhite commented on index.js
> +    delete devLog.error_data;
And if this object is scoped to the function, you don't have to `delete` which is generally a bad idea it can cause memory leaks and weird stuff to take place in the v8 machinery

2021-06-01 17:31 UTC, braxtonj commented on index.js
> +    devLog.why = 'uncaught exception - '+err.message;
it was originally at the end of the file, outside of the main function.  but testing with some throws it wasn't working unless I define it first.  happy to move into the actual parsing function though

2021-06-01 17:33 UTC, braxtonj commented on index.js
> +    delete devLog.error_data;
mostly just trying to clean up the error_data content so it isn't included with other developer logs.  alternate is to create a new object for error logs and use that.  will switch that up to avoid memory leaks this evening

2021-06-01 17:33 UTC, esatterwhite commented on index.js
> +                    devLog.why = 'regex failed to validate'
Ah, I see whats going on with `devLog`
you might just make a function that returns a formatted object rather than clobbering properties in place

```javascript
const output = devLog({
  what: 'LogDNA Account registration'
, when: new Date().toISOString()
})
```

Re-using singleton objects like this is what I would call a "foot-gun"

2021-06-01 17:35 UTC, esatterwhite commented on index.js
> +                                        return process.exit(0); // Hard fail
do you want to exit with a non-zero code here? This will seem like everything is ok for things that might be watching for exit codes

2021-06-01 17:37 UTC, braxtonj commented on index.js
> +                                        return process.exit(0); // Hard fail
just following the prior error code here.  they exited the process at this point using the old utils.log code

2021-06-01 17:38 UTC, braxtonj commented on index.js
> +                                        return process.exit(0); // Hard fail
just reusing the prior error logic here.  they exited the process at this point with the old config.log function so I did the same

2021-06-01 17:39 UTC, braxtonj commented on index.js
> +                    devLog.why = 'regex failed to validate'
oooo that makes more sense, will re-write to use a function

2021-06-01 18:04 UTC, mdeltito commented on index.js
> +                    let from_date = tf_obj.start.date();
nit: should stick to `tfObj` and `fromDate` casing for consistency

2021-06-01 18:04 UTC, mdeltito commented on package.json
> +    "@logdna/logger": "^2.3.2",
if we make this a "real" feature with a flag, this would need to go in `dependencies`

2021-06-01 21:43 UTC, braxtonj commented on index.js
> +                    devLog.why = 'regex failed to validate'
new commit coming has this as a primitive function in lib/utils.js

2021-06-01 21:44 UTC, braxtonj commented on index.js
> +if (config.DEV) {
i like this.  implemented as a flag via commander.  -d and --dev

2021-06-01 21:44 UTC, braxtonj commented on index.js
> +                        return process.exit(0); // Hard fail
commit coming has exit(1)'s

2021-06-01 21:44 UTC, braxtonj commented on package.json
> +    "@logdna/logger": "^2.3.2",
moved to `dependencies`

2021-06-02 00:04 UTC, braxtonj commented on index.js
> +    devLog.why = 'uncaught exception - '+err.message;
ah misread your comment.  updated commit has staggering of variables when needed, otherwise defined in function call now 👌

2021-06-02 00:06 UTC, braxtonj commented on index.js
> +                                        return process.exit(0); // Hard fail
updated all with exit(1) to signify a non-ok event.  thanks for pointing this out @esatterwhite!

2021-06-02 09:10 UTC, jorgebay requested changes
Supporting natural language for date/time in the cli is a great idea, I've added some remarks below.

Ideally, we should large PRs into smaller ones (e.g  a PR for date time parsing and another for "dev" logs) to make it easier to review and land.

2021-06-02 09:10 UTC, jorgebay commented on README.md
> +$ logdna search "logdna" --from "yesterday at 3pm" to "today at 3:05pm"
This should be

```suggestion
$ logdna search "logdna" --from "yesterday at 3pm" --to "today at 3:05pm"
```

2021-06-02 09:10 UTC, jorgebay commented on README.md
> +$ logdna search "logdna" --from "yesterday at 3pm" to "today at 3:05pm"
This should be

```suggestion
$ logdna search "logdna" --from "yesterday at 3pm" --to "today at 3:05pm"
```

2021-06-02 09:10 UTC, jorgebay commented on index.js
> +                            let tfObj = chrono.parse(options.from)[0];
We should handle any call to `chrono.parse()` that might return an empty array (nothing could be parsed)

2021-06-02 16:31 UTC, braxtonj commented on CHANGELOG.md
> +- Add "today" when a date reference isn't explicity included (ie `search --from "7PM" --to "8PM"` instead of `search --from "today at 7PM" --to "today at 8PM"`)
Happy to add some Jiras for these.  But left them in the CHANGELOG to keep it open to the community

2021-06-02 16:42 UTC, nimbinatus requested changes
Couple grammar notes and a confusing sentence

2021-06-02 16:42 UTC, nimbinatus commented on CONTRIBUTING.md
> +The easiest way to get our attention is to comment on an existing, or open a new
```suggestion
The easiest way to get our attention is to comment on an existing or open a new
```

2021-06-02 16:42 UTC, nimbinatus commented on README.md
> +Logs for troubleshooting during development are included.  These will pipe to both console and [LogDNA](https://www.logdna.com/).
```suggestion
Logs for troubleshooting during development are included. These logs will pipe both to console and [LogDNA](https://www.logdna.com/).
```

2021-06-02 16:42 UTC, nimbinatus commented on README.md
> +Switch dev logs on via the `-d` or `--dev` flag
```suggestion
Switch dev logs on via the `-d` or `--dev` flag.
```

2021-06-02 16:42 UTC, nimbinatus commented on README.md
> +Specify a log as "dev" by using logger.log(...)
```suggestion
Specify a log as "dev" by using `logger.log(...)`.
```

2021-06-02 16:42 UTC, nimbinatus commented on README.md
> +Note that we have used a standard log primitive via lib/utils.js -> devLogPrim() with "what", "why", "where", "who" and "when" to ensure full context is included as well as a "message" field for quic
Agreed. This could be an interesting blog post or Discourse discussion, though.

2021-06-02 16:42 UTC, nimbinatus commented on README.md
> +Currently the coverage is limited to index.js and more heavily in --timeframe, --from and --to.
```suggestion
Currently the coverage is limited to index.js and more heavily in `--timeframe`, `--from`, and `--to`.
```

To be honest, I have no idea what this sentence means, but it may be that I just don't know the package (which is also true and very likely). What do you mean that it's limited to a specific file but heavily to a set of flags?

2021-06-02 16:49 UTC, braxtonj commented on README.md
> +Note that we have used a standard log primitive via lib/utils.js -> devLogPrim() with "what", "why", "where", "who" and "when" to ensure full context is included as well as a "message" field for quic
moved to be a comment in index.js.  Love the idea of a Discourse discussion on the topic

2021-06-02 16:49 UTC, braxtonj commented on README.md
> +Requires LogDNA account with environment variable LOGDNA_API_KEY see logs in LogDNA
Fixed

2021-06-02 16:50 UTC, braxtonj commented on index.js
> +let logger = logdna.createLogger(
Modifed code to use winston with the console transport and logdna-winston transport IF the env var LOGDNA_API_KEY is set

2021-06-02 16:50 UTC, braxtonj commented on README.md
> +$ logdna search "logdna" --from "yesterday at 3pm" to "today at 3:05pm"
fixed

2021-06-02 16:51 UTC, braxtonj commented on README.md
> +$ logdna search "logdna" --from "yesterday at 3pm" to "today at 3:05pm"
fixed

2021-06-02 16:51 UTC, braxtonj commented on index.js
> +                            let tfObj = chrono.parse(options.from)[0];
definitely a good callout.  fixed to ignore if this returns empty.

2021-06-02 16:55 UTC, braxtonj commented on README.md
> +Currently the coverage is limited to index.js and more heavily in --timeframe, --from and --to.
simply that there are no developer specific logs in any logic outside of `--timeframe`, `--from` and `--to`

2021-06-02 16:56 UTC, braxtonj commented on CONTRIBUTING.md
> +The easiest way to get our attention is to comment on an existing, or open a new
fixed

2021-06-02 16:56 UTC, braxtonj commented on README.md
> +Logs for troubleshooting during development are included.  These will pipe to both console and [LogDNA](https://www.logdna.com/).
fixed

2021-06-02 16:56 UTC, braxtonj commented on README.md
> +Specify a log as "dev" by using logger.log(...)
fixed

2021-06-02 16:56 UTC, braxtonj commented on README.md
> +Switch dev logs on via the `-d` or `--dev` flag
fixed

2021-06-02 17:03 UTC, esatterwhite commented on lib/utils.js
> +    return logPrim;
I think this could be simplified quite a bit. type checking in javascript is a bit of a dark art and I'd avoid trying to do too much of it if possible

```javascript
function devLogPrim(opts) {
  const {
    message = ''
  , who = 'dev'
  , what = ''
  , why = ''
  , when = new Date().ToISOString()
  , additional = {}
  } = opts

  return {
    message
  , who
  , what
  , why
  , where
  , when
  , ...additional
  }
}
```
in this case any `undefined` properties will fall back to the defaults.

2021-06-02 17:06 UTC, esatterwhite commented on package.json
> +  "version": "2.1.0",
Oh, I wouldn't tick this version manually just yet. 
This should be done separately after it is merged and ready to be released.

The release process on this doesn't look to be automated yet. We should open issue to set that up.

2021-06-02 17:09 UTC, esatterwhite commented on scripts/logdna.nuspec
> +    <copyright>Copyright 2021 LogDNA, Inc., portions by Microsoft and Contributors</copyright>
the copyright year should be to year of original publishing, not the current year.
The year indicates how far back the claim to this work is made. So this would basically be disowning everything before 2021

2021-06-02 17:17 UTC, braxtonj commented on lib/utils.js
> +    return logPrim;
the dark arts of javascript.  updated 😁

2021-06-02 17:23 UTC, braxtonj commented on package.json
> +  "version": "2.1.0",
Fair enough, reverting to 2.0.0 everywhere, including the changelog.

Fixed

2021-06-02 17:23 UTC, braxtonj commented on scripts/logdna.nuspec
> +    <copyright>Copyright 2021 LogDNA, Inc., portions by Microsoft and Contributors</copyright>
Ah that would definitely not be good.  Changed back to 2020 :)

2021-06-02 20:15 UTC, braxtonj commented on CHANGELOG.md
> +- Add "today" when a date reference isn't explicity included (ie `search --from "7PM" --to "8PM"` instead of `search --from "today at 7PM" --to "today at 8PM"`)
Removed from Changelog.  Will be opening "Issues" for further work ideas for the community (the TODOs) once this is merged.

2021-06-03 08:32 UTC, jorgebay approved these changes
I've added a couple of comments below but nothing blocking.

The ease of use is greatly improved with this PR. We should cover these changes and existing functionality as soon as possible.

2021-06-03 08:32 UTC, jorgebay commented on index.js
> +let logger = winston.createLogger({
NIT: It should be `const`

2021-06-03 08:32 UTC, jorgebay commented on index.js
> +                    }
I think this kind of logic can be extracted and reused across most commands.

We should be interested in logging the command w/ options at debug level and the error itself as it is catched at 'error' level. One or two command handlers might need additional info but not all of them.

2021-06-03 14:26 UTC, braxtonj commented on CHANGELOG.md
> +## [v2.0.0] - 2021-06-01
updated 👍

2021-06-03 14:26 UTC, braxtonj commented on index.js
> +let logger = winston.createLogger({
updated anyway ha ha

2021-06-03 14:27 UTC, jorgebay approved these changes

2021-06-03 16:28 UTC, braxtonj commented on index.js
> +                    }
saving for a diff PR

2021-06-03 18:54 UTC, braxtonj commented on README.md
> +Currently the coverage is limited to index.js and more heavily in --timeframe, --from and --to.
reworded

2021-06-03 19:04 UTC, jorgebay approved these changes

2021-06-08 16:07 UTC, nimbinatus reviewed
just a couple nits; non blockers

2021-06-08 16:07 UTC, nimbinatus commented on README.md
> +# Ensure to enclose nl strings in ""
```suggestion
# Ensure to enclose natural langauge strings in ""
```

Nit: People may not immediately get the acronym; generally, docs shouldn't have acronyms without explaining them at least once.

2021-06-08 16:07 UTC, nimbinatus commented on README.md
> +# Must include date reference, IE May 26, yesterday or the like
```suggestion
# Must include date reference (i.e., `May 26`, `yesterday`, or the like)
```

2021-06-08 16:46 UTC, nimbinatus approved these changes

2021-06-08 19:28 UTC, jorgebay approved these changes

2021-06-09 07:26 UTC, merged